### ISSUE TITLE
Can't create a new file OR open a file!

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Solid-Edge-for-Linux#1]
### The installation of Solid Edge went very well. :+1: 

However, I get this message when I want to create a new project:

![#4-first-start](https://user-images.githubusercontent.com/79079633/153579799-283a90e6-113d-4266-b42c-c97aaaca08b9.png)

**Comment by cryinkfly** [comment]
I get also a error in the terminal: err:mshtml:on_stop_nsrequest RemoveRequest failed: 80004005

**Comment by cryinkfly** [comment]
I found this error also here: https://community.sw.siemens.com/s/question/0D54O000061xetISAQ/cannot-open-file-make-sure-the-file-is-the-correct-type

**Comment by vintagepc** [comment]
I've regularly been testing the latest wine-staging hoping it's been fixed to no avail. 

My suspicion is this seems related to some changes in how the file-open dialog is handled in Win7+ that isn't quite supported by WINE yet unfortunately :( This error has stymied my efforts all the way back to SE2020.

**Comment by cryinkfly** [comment]
@vintagepc Okay, thanks for this information! :+1: 

Because that might help me to fix this issue.

**Comment by cryinkfly** [comment]
# I have solved this issue with the newest wine version and with setting up Windows 11 in the Wine configuration! :100: 

![Bildschirmfoto vom 2023-03-14 17-47-42](https://user-images.githubusercontent.com/79079633/225077701-bf6f84a5-3c04-4354-bac7-3eab36e8f355.png)

But Solid Edge is at the moment not stable enough!

Here can you see a short video: https://youtu.be/Jo30dFYeXxE

**Comment by vintagepc** [comment]
Does this work with older versions like 2022/21? They changed the licensing recently so that it's no longer perpetual and only valid for 3 years. Which would be problematic if future versions become totally incompatible

**Comment by cryinkfly** [comment]
@vintagepc Unfortunately I can't tell you that because I don't have an older version. You can only try it. :-)

**Comment by vintagepc** [comment]
2020: :no_entry: seems like it's opening/creating the document Just dumps you back to the home screen.
2021: :no_entry: Crashes on creating.
2022: :question: Sort of. Attempting to do anything causes an out-of-memory error and it shuts down.
2023: same as 2022 for me. 

Wine version 8.3

**Comment by cryinkfly** [comment]
Which graphics card did you install?

**Comment by vintagepc** [comment]
My mistake, I mixed up my directories when testing. SE2023 doesn't crash, instead I get a window with a blank dialog and it does a weird "capture" of my cursor so I can no longer click anything, I have to alt-tab to the terminal and ctrl-c it to regain control of the desktop.

I have a GTX1050 installed with proprietary drivers. Tried both with and without DXVK installed. 

![image](https://user-images.githubusercontent.com/53943260/225123156-a47c5586-1b67-4dd8-85e3-31ae7bfdd163.png)

**Comment by cryinkfly** [comment]
Okay, I'm running it with an AMD Radeon™ RX 6400 without DXVK currently.

Did you create a new wineprefix?

**Comment by vintagepc** [comment]
Yeah, I have different prefixes into which I've installed all four editions I have copies of.  It was installed under w10 mode. I can try nuking the prefix and starting clean to see if it makes a difference later today.

**Comment by vintagepc** [comment]
Fresh install fixes that dialog, but after a few moments it still reports "Solid Edge is closing because the system is out of memory"

**Comment by vintagepc** [comment]
Just watched the video, I see you are a fellow openSuSE user ;)
