### ISSUE TITLE
Addition steps needed to get it to install

### ISSUE THREAD

**Issue by dzervas** [cryinkfly/Solid-Edge-for-Linux#2]
I needed to do this to get it to install:

```bash
export WINEPREFIX="$HOME/.wineprefixes/solidedge"
winecfg -q win10
```

**Comment by cryinkfly** [comment]
WINEPREFIX="$HOME/.wineprefixes/solidedge" winetricks -q win11
    WINEPREFIX="$HOME/.wineprefixes/solidedge" wine Solid*.exe
